name: CI - Web

on:
  pull_request:
    branches: [develop, main]
    paths:
      - "apps/web/**"
      - "packages/**"
      - "package-lock.json"
      - "turbo.json"

jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Lint
        run: npm run lint -- --filter=web...

      - name: Build
        run: npm run build -- --filter=web...

      - name: Testes
        run: npm run test -- --filter=web...
